### ISSUE TITLE
Replicating Adversarial Training Paper

### ISSUE THREAD

**Issue by nvidiaman** [Alexander-H-Liu/End-to-end-ASR-Pytorch#15]
Hello,

can you provide the commands to replicate the results of the paper?

It will also be helpful for people running other models.

Thank you

**Comment by Alexander-H-Liu** [comment]
Hi @nvidiaman,

Thanks for your attention to our project, simply enable the option in the example config will do the job.
However, hyperparameter tuning may be required on different datasets (models)
You'll also find the performance is slightly better than the paper since it's based on worth implementation (which derived from other repo as described in the paper) by the time. 

Thanks again!

p.s. please consider email me if you have any bug-irrelevant questions like this one or #12, I'm more reachable in that way XD.
