### ISSUE TITLE
Single audio inference

### ISSUE THREAD

**Issue by iamxiaoyubei** [Alexander-H-Liu/End-to-end-ASR-Pytorch#33]
How does your code make inference? That is, I pass in an audio, and the code outputs the audio recognition result.

**Comment by Youyoun** [comment]
Hi @iamxiaoyubei ,

Maybe I'm wrong, but this repo does not provide a means to infer a single audio. You'll have to write your own script to do that. 

It shouldn't be that hard, since all the functions you need for converting data are already implemented, all you have to do is use them.

This repo seems more like a research framework, where you preprocess fixed sets of data and train different models on the same data in order to compare them. 

If you really want a small turnaround, you could run `preprocess_corpus.py` on a folder with a structure similar to the training data. and then run the test on that folder.

**Comment by iamxiaoyubei** [comment]
I understand. Thank you~！

**Comment by shamil-kadavan** [comment]
Hi @iamxiaoyubei,
I am a newbie to this field. Can you please guide me through?
